//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HISWebApi.TallyServerProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoucherData", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class VoucherData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrLedgerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrLedgerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoucherDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoucherNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrLedger {
            get {
                return this.CrLedgerField;
            }
            set {
                if ((object.ReferenceEquals(this.CrLedgerField, value) != true)) {
                    this.CrLedgerField = value;
                    this.RaisePropertyChanged("CrLedger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DrLedger {
            get {
                return this.DrLedgerField;
            }
            set {
                if ((object.ReferenceEquals(this.DrLedgerField, value) != true)) {
                    this.DrLedgerField = value;
                    this.RaisePropertyChanged("DrLedger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenFrom {
            get {
                return this.GenFromField;
            }
            set {
                if ((object.ReferenceEquals(this.GenFromField, value) != true)) {
                    this.GenFromField = value;
                    this.RaisePropertyChanged("GenFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNo {
            get {
                return this.InvoiceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNoField, value) != true)) {
                    this.InvoiceNoField = value;
                    this.RaisePropertyChanged("InvoiceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Narration {
            get {
                return this.NarrationField;
            }
            set {
                if ((object.ReferenceEquals(this.NarrationField, value) != true)) {
                    this.NarrationField = value;
                    this.RaisePropertyChanged("Narration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VchType {
            get {
                return this.VchTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VchTypeField, value) != true)) {
                    this.VchTypeField = value;
                    this.RaisePropertyChanged("VchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoucherDate {
            get {
                return this.VoucherDateField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherDateField, value) != true)) {
                    this.VoucherDateField = value;
                    this.RaisePropertyChanged("VoucherDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoucherNo {
            get {
                return this.VoucherNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherNoField, value) != true)) {
                    this.VoucherNoField = value;
                    this.RaisePropertyChanged("VoucherNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiagSalesSummary", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DiagSalesSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CurSalesReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldPfRebateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldRebateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldRebateReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldReceivableReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldReceivedReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldSalesReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RebateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalSalesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurSalesReturn {
            get {
                return this.CurSalesReturnField;
            }
            set {
                if ((this.CurSalesReturnField.Equals(value) != true)) {
                    this.CurSalesReturnField = value;
                    this.RaisePropertyChanged("CurSalesReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldPfRebate {
            get {
                return this.OldPfRebateField;
            }
            set {
                if ((this.OldPfRebateField.Equals(value) != true)) {
                    this.OldPfRebateField = value;
                    this.RaisePropertyChanged("OldPfRebate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldRebate {
            get {
                return this.OldRebateField;
            }
            set {
                if ((this.OldRebateField.Equals(value) != true)) {
                    this.OldRebateField = value;
                    this.RaisePropertyChanged("OldRebate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldRebateReturn {
            get {
                return this.OldRebateReturnField;
            }
            set {
                if ((this.OldRebateReturnField.Equals(value) != true)) {
                    this.OldRebateReturnField = value;
                    this.RaisePropertyChanged("OldRebateReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldReceivableReturn {
            get {
                return this.OldReceivableReturnField;
            }
            set {
                if ((this.OldReceivableReturnField.Equals(value) != true)) {
                    this.OldReceivableReturnField = value;
                    this.RaisePropertyChanged("OldReceivableReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldReceived {
            get {
                return this.OldReceivedField;
            }
            set {
                if ((this.OldReceivedField.Equals(value) != true)) {
                    this.OldReceivedField = value;
                    this.RaisePropertyChanged("OldReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldReceivedReturn {
            get {
                return this.OldReceivedReturnField;
            }
            set {
                if ((this.OldReceivedReturnField.Equals(value) != true)) {
                    this.OldReceivedReturnField = value;
                    this.RaisePropertyChanged("OldReceivedReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldSalesReturn {
            get {
                return this.OldSalesReturnField;
            }
            set {
                if ((this.OldSalesReturnField.Equals(value) != true)) {
                    this.OldSalesReturnField = value;
                    this.RaisePropertyChanged("OldSalesReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rebate {
            get {
                return this.RebateField;
            }
            set {
                if ((this.RebateField.Equals(value) != true)) {
                    this.RebateField = value;
                    this.RaisePropertyChanged("Rebate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Received {
            get {
                return this.ReceivedField;
            }
            set {
                if ((this.ReceivedField.Equals(value) != true)) {
                    this.ReceivedField = value;
                    this.RaisePropertyChanged("Received");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSales {
            get {
                return this.TotalSalesField;
            }
            set {
                if ((this.TotalSalesField.Equals(value) != true)) {
                    this.TotalSalesField = value;
                    this.RaisePropertyChanged("TotalSales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupData", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class GroupData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrpNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrpName {
            get {
                return this.GrpNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GrpNameField, value) != true)) {
                    this.GrpNameField = value;
                    this.RaisePropertyChanged("GrpName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LedgerData", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class LedgerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LedgerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpBalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LedgerName {
            get {
                return this.LedgerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LedgerNameField, value) != true)) {
                    this.LedgerNameField = value;
                    this.RaisePropertyChanged("LedgerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name2 {
            get {
                return this.Name2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name2Field, value) != true)) {
                    this.Name2Field = value;
                    this.RaisePropertyChanged("Name2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpBalance {
            get {
                return this.OpBalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.OpBalanceField, value) != true)) {
                    this.OpBalanceField = value;
                    this.RaisePropertyChanged("OpBalance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaryInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class SalaryInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdvancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BasicLedgerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BasicSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FixedConveyanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HRAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayableSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReimburshmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryProcessDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialAllowanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxDedAtSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeleAllowanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WashingAllowanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string creditAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string debitAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exgratiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string medicalAllowanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string narrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trustDeductionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Advances {
            get {
                return this.AdvancesField;
            }
            set {
                if ((object.ReferenceEquals(this.AdvancesField, value) != true)) {
                    this.AdvancesField = value;
                    this.RaisePropertyChanged("Advances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BasicLedger {
            get {
                return this.BasicLedgerField;
            }
            set {
                if ((object.ReferenceEquals(this.BasicLedgerField, value) != true)) {
                    this.BasicLedgerField = value;
                    this.RaisePropertyChanged("BasicLedger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BasicSalary {
            get {
                return this.BasicSalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.BasicSalaryField, value) != true)) {
                    this.BasicSalaryField = value;
                    this.RaisePropertyChanged("BasicSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((object.ReferenceEquals(this.BonusField, value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESI {
            get {
                return this.ESIField;
            }
            set {
                if ((object.ReferenceEquals(this.ESIField, value) != true)) {
                    this.ESIField = value;
                    this.RaisePropertyChanged("ESI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpCode {
            get {
                return this.EmpCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpCodeField, value) != true)) {
                    this.EmpCodeField = value;
                    this.RaisePropertyChanged("EmpCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpName {
            get {
                return this.EmpNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNameField, value) != true)) {
                    this.EmpNameField = value;
                    this.RaisePropertyChanged("EmpName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpStatus {
            get {
                return this.EmpStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpStatusField, value) != true)) {
                    this.EmpStatusField = value;
                    this.RaisePropertyChanged("EmpStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FixedConveyance {
            get {
                return this.FixedConveyanceField;
            }
            set {
                if ((object.ReferenceEquals(this.FixedConveyanceField, value) != true)) {
                    this.FixedConveyanceField = value;
                    this.RaisePropertyChanged("FixedConveyance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HRA {
            get {
                return this.HRAField;
            }
            set {
                if ((object.ReferenceEquals(this.HRAField, value) != true)) {
                    this.HRAField = value;
                    this.RaisePropertyChanged("HRA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Loan {
            get {
                return this.LoanField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanField, value) != true)) {
                    this.LoanField = value;
                    this.RaisePropertyChanged("Loan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PF {
            get {
                return this.PFField;
            }
            set {
                if ((object.ReferenceEquals(this.PFField, value) != true)) {
                    this.PFField = value;
                    this.RaisePropertyChanged("PF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayableSalary {
            get {
                return this.PayableSalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.PayableSalaryField, value) != true)) {
                    this.PayableSalaryField = value;
                    this.RaisePropertyChanged("PayableSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reimburshment {
            get {
                return this.ReimburshmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ReimburshmentField, value) != true)) {
                    this.ReimburshmentField = value;
                    this.RaisePropertyChanged("Reimburshment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalaryProcessDate {
            get {
                return this.SalaryProcessDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryProcessDateField, value) != true)) {
                    this.SalaryProcessDateField = value;
                    this.RaisePropertyChanged("SalaryProcessDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialAllowance {
            get {
                return this.SpecialAllowanceField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialAllowanceField, value) != true)) {
                    this.SpecialAllowanceField = value;
                    this.RaisePropertyChanged("SpecialAllowance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxDedAtSource {
            get {
                return this.TaxDedAtSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxDedAtSourceField, value) != true)) {
                    this.TaxDedAtSourceField = value;
                    this.RaisePropertyChanged("TaxDedAtSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeleAllowance {
            get {
                return this.TeleAllowanceField;
            }
            set {
                if ((object.ReferenceEquals(this.TeleAllowanceField, value) != true)) {
                    this.TeleAllowanceField = value;
                    this.RaisePropertyChanged("TeleAllowance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIDField, value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WashingAllowance {
            get {
                return this.WashingAllowanceField;
            }
            set {
                if ((object.ReferenceEquals(this.WashingAllowanceField, value) != true)) {
                    this.WashingAllowanceField = value;
                    this.RaisePropertyChanged("WashingAllowance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string creditAccount {
            get {
                return this.creditAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.creditAccountField, value) != true)) {
                    this.creditAccountField = value;
                    this.RaisePropertyChanged("creditAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string debitAccount {
            get {
                return this.debitAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.debitAccountField, value) != true)) {
                    this.debitAccountField = value;
                    this.RaisePropertyChanged("debitAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string exgratia {
            get {
                return this.exgratiaField;
            }
            set {
                if ((object.ReferenceEquals(this.exgratiaField, value) != true)) {
                    this.exgratiaField = value;
                    this.RaisePropertyChanged("exgratia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string medicalAllowance {
            get {
                return this.medicalAllowanceField;
            }
            set {
                if ((object.ReferenceEquals(this.medicalAllowanceField, value) != true)) {
                    this.medicalAllowanceField = value;
                    this.RaisePropertyChanged("medicalAllowance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string narration {
            get {
                return this.narrationField;
            }
            set {
                if ((object.ReferenceEquals(this.narrationField, value) != true)) {
                    this.narrationField = value;
                    this.RaisePropertyChanged("narration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trustDeduction {
            get {
                return this.trustDeductionField;
            }
            set {
                if ((object.ReferenceEquals(this.trustDeductionField, value) != true)) {
                    this.trustDeductionField = value;
                    this.RaisePropertyChanged("trustDeduction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoucherDataVertical", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class VoucherDataVertical : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeqNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoucherNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ledgernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Narration {
            get {
                return this.NarrationField;
            }
            set {
                if ((object.ReferenceEquals(this.NarrationField, value) != true)) {
                    this.NarrationField = value;
                    this.RaisePropertyChanged("Narration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeqNo {
            get {
                return this.SeqNoField;
            }
            set {
                if ((this.SeqNoField.Equals(value) != true)) {
                    this.SeqNoField = value;
                    this.RaisePropertyChanged("SeqNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoucherNo {
            get {
                return this.VoucherNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherNoField, value) != true)) {
                    this.VoucherNoField = value;
                    this.RaisePropertyChanged("VoucherNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string billNo {
            get {
                return this.billNoField;
            }
            set {
                if ((object.ReferenceEquals(this.billNoField, value) != true)) {
                    this.billNoField = value;
                    this.RaisePropertyChanged("billNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string billType {
            get {
                return this.billTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.billTypeField, value) != true)) {
                    this.billTypeField = value;
                    this.RaisePropertyChanged("billType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ledgername {
            get {
                return this.ledgernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ledgernameField, value) != true)) {
                    this.ledgernameField = value;
                    this.RaisePropertyChanged("ledgername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchDate {
            get {
                return this.vchDateField;
            }
            set {
                if ((object.ReferenceEquals(this.vchDateField, value) != true)) {
                    this.vchDateField = value;
                    this.RaisePropertyChanged("vchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchType {
            get {
                return this.vchTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.vchTypeField, value) != true)) {
                    this.vchTypeField = value;
                    this.RaisePropertyChanged("vchType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TallyServerProxy.ITallyAdapterService")]
    public interface ITallyAdapterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertDiagnosticSales_1314", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertDiagnosticSales_1314Response")]
        string Tally_InsertDiagnosticSales_1314(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, HISWebApi.TallyServerProxy.DiagSalesSummary dss, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertDiagnosticSales_1314", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertDiagnosticSales_1314Response")]
        System.Threading.Tasks.Task<string> Tally_InsertDiagnosticSales_1314Async(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, HISWebApi.TallyServerProxy.DiagSalesSummary dss, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertDiagnosticSales_CurFinYear", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertDiagnosticSales_CurFinYearRes" +
            "ponse")]
        string Tally_InsertDiagnosticSales_CurFinYear(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, HISWebApi.TallyServerProxy.DiagSalesSummary dss, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertDiagnosticSales_CurFinYear", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertDiagnosticSales_CurFinYearRes" +
            "ponse")]
        System.Threading.Tasks.Task<string> Tally_InsertDiagnosticSales_CurFinYearAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, HISWebApi.TallyServerProxy.DiagSalesSummary dss, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertPharmacySales", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertPharmacySalesResponse")]
        string Tally_InsertPharmacySales(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertPharmacySales", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertPharmacySalesResponse")]
        System.Threading.Tasks.Task<string> Tally_InsertPharmacySalesAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_CreateGroup", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_CreateGroupResponse")]
        string Tally_CreateGroup(System.Collections.Generic.List<HISWebApi.TallyServerProxy.GroupData> groups, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_CreateGroup", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_CreateGroupResponse")]
        System.Threading.Tasks.Task<string> Tally_CreateGroupAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.GroupData> groups, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_CreateLedger", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_CreateLedgerResponse")]
        string Tally_CreateLedger(System.Collections.Generic.List<HISWebApi.TallyServerProxy.LedgerData> ledgers, string Company, string Action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_CreateLedger", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_CreateLedgerResponse")]
        System.Threading.Tasks.Task<string> Tally_CreateLedgerAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.LedgerData> ledgers, string Company, string Action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertVouchers", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertVouchersResponse")]
        string Tally_InsertVouchers(HISWebApi.TallyServerProxy.VoucherData obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertVouchers", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertVouchersResponse")]
        System.Threading.Tasks.Task<string> Tally_InsertVouchersAsync(HISWebApi.TallyServerProxy.VoucherData obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertVouchers_Bulk", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertVouchers_BulkResponse")]
        string Tally_InsertVouchers_Bulk(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vchList, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_InsertVouchers_Bulk", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_InsertVouchers_BulkResponse")]
        System.Threading.Tasks.Task<string> Tally_InsertVouchers_BulkAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vchList, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_ModifyVoucher", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_ModifyVoucherResponse")]
        string Tally_ModifyVoucher(HISWebApi.TallyServerProxy.VoucherData obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_ModifyVoucher", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_ModifyVoucherResponse")]
        System.Threading.Tasks.Task<string> Tally_ModifyVoucherAsync(HISWebApi.TallyServerProxy.VoucherData obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_ImportData", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_ImportDataResponse")]
        string Tally_ImportData(string Company, string RequestType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_ImportData", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_ImportDataResponse")]
        System.Threading.Tasks.Task<string> Tally_ImportDataAsync(string Company, string RequestType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_ModifyVouchers1", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_ModifyVouchers1Response")]
        string Tally_ModifyVouchers1(HISWebApi.TallyServerProxy.VoucherData obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_ModifyVouchers1", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_ModifyVouchers1Response")]
        System.Threading.Tasks.Task<string> Tally_ModifyVouchers1Async(HISWebApi.TallyServerProxy.VoucherData obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_PharmacyVoucherEntry", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_PharmacyVoucherEntryResponse")]
        string Tally_PharmacyVoucherEntry(HISWebApi.TallyServerProxy.VoucherData obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_PharmacyVoucherEntry", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_PharmacyVoucherEntryResponse")]
        System.Threading.Tasks.Task<string> Tally_PharmacyVoucherEntryAsync(HISWebApi.TallyServerProxy.VoucherData obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_PharmacyVoucherEntryTemp", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_PharmacyVoucherEntryTempResponse")]
        string Tally_PharmacyVoucherEntryTemp(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_PharmacyVoucherEntryTemp", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_PharmacyVoucherEntryTempResponse")]
        System.Threading.Tasks.Task<string> Tally_PharmacyVoucherEntryTempAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_SalaryEntry", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_SalaryEntryResponse")]
        string Tally_SalaryEntry(HISWebApi.TallyServerProxy.SalaryInfo obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_SalaryEntry", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_SalaryEntryResponse")]
        System.Threading.Tasks.Task<string> Tally_SalaryEntryAsync(HISWebApi.TallyServerProxy.SalaryInfo obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_DonationEntry", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_DonationEntryResponse")]
        string Tally_DonationEntry(HISWebApi.TallyServerProxy.SalaryInfo obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_DonationEntry", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_DonationEntryResponse")]
        System.Threading.Tasks.Task<string> Tally_DonationEntryAsync(HISWebApi.TallyServerProxy.SalaryInfo obj, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/CompanyNameForTally", ReplyAction="http://tempuri.org/ITallyAdapterService/CompanyNameForTallyResponse")]
        string CompanyNameForTally(string comp_code, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/CompanyNameForTally", ReplyAction="http://tempuri.org/ITallyAdapterService/CompanyNameForTallyResponse")]
        System.Threading.Tasks.Task<string> CompanyNameForTallyAsync(string comp_code, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_VoucherEntryNew", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_VoucherEntryNewResponse")]
        string Tally_VoucherEntryNew(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherDataVertical> obj, string VoucherType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITallyAdapterService/Tally_VoucherEntryNew", ReplyAction="http://tempuri.org/ITallyAdapterService/Tally_VoucherEntryNewResponse")]
        System.Threading.Tasks.Task<string> Tally_VoucherEntryNewAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherDataVertical> obj, string VoucherType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITallyAdapterServiceChannel : HISWebApi.TallyServerProxy.ITallyAdapterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TallyAdapterServiceClient : System.ServiceModel.ClientBase<HISWebApi.TallyServerProxy.ITallyAdapterService>, HISWebApi.TallyServerProxy.ITallyAdapterService {
        
        public TallyAdapterServiceClient() {
        }
        
        public TallyAdapterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TallyAdapterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TallyAdapterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TallyAdapterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Tally_InsertDiagnosticSales_1314(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, HISWebApi.TallyServerProxy.DiagSalesSummary dss, string Company) {
            return base.Channel.Tally_InsertDiagnosticSales_1314(vouchers, dss, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_InsertDiagnosticSales_1314Async(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, HISWebApi.TallyServerProxy.DiagSalesSummary dss, string Company) {
            return base.Channel.Tally_InsertDiagnosticSales_1314Async(vouchers, dss, Company);
        }
        
        public string Tally_InsertDiagnosticSales_CurFinYear(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, HISWebApi.TallyServerProxy.DiagSalesSummary dss, string Company) {
            return base.Channel.Tally_InsertDiagnosticSales_CurFinYear(vouchers, dss, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_InsertDiagnosticSales_CurFinYearAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, HISWebApi.TallyServerProxy.DiagSalesSummary dss, string Company) {
            return base.Channel.Tally_InsertDiagnosticSales_CurFinYearAsync(vouchers, dss, Company);
        }
        
        public string Tally_InsertPharmacySales(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, string Company) {
            return base.Channel.Tally_InsertPharmacySales(vouchers, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_InsertPharmacySalesAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vouchers, string Company) {
            return base.Channel.Tally_InsertPharmacySalesAsync(vouchers, Company);
        }
        
        public string Tally_CreateGroup(System.Collections.Generic.List<HISWebApi.TallyServerProxy.GroupData> groups, string Company) {
            return base.Channel.Tally_CreateGroup(groups, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_CreateGroupAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.GroupData> groups, string Company) {
            return base.Channel.Tally_CreateGroupAsync(groups, Company);
        }
        
        public string Tally_CreateLedger(System.Collections.Generic.List<HISWebApi.TallyServerProxy.LedgerData> ledgers, string Company, string Action) {
            return base.Channel.Tally_CreateLedger(ledgers, Company, Action);
        }
        
        public System.Threading.Tasks.Task<string> Tally_CreateLedgerAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.LedgerData> ledgers, string Company, string Action) {
            return base.Channel.Tally_CreateLedgerAsync(ledgers, Company, Action);
        }
        
        public string Tally_InsertVouchers(HISWebApi.TallyServerProxy.VoucherData obj, string Company) {
            return base.Channel.Tally_InsertVouchers(obj, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_InsertVouchersAsync(HISWebApi.TallyServerProxy.VoucherData obj, string Company) {
            return base.Channel.Tally_InsertVouchersAsync(obj, Company);
        }
        
        public string Tally_InsertVouchers_Bulk(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vchList, string Company) {
            return base.Channel.Tally_InsertVouchers_Bulk(vchList, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_InsertVouchers_BulkAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherData> vchList, string Company) {
            return base.Channel.Tally_InsertVouchers_BulkAsync(vchList, Company);
        }
        
        public string Tally_ModifyVoucher(HISWebApi.TallyServerProxy.VoucherData obj, string Company) {
            return base.Channel.Tally_ModifyVoucher(obj, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_ModifyVoucherAsync(HISWebApi.TallyServerProxy.VoucherData obj, string Company) {
            return base.Channel.Tally_ModifyVoucherAsync(obj, Company);
        }
        
        public string Tally_ImportData(string Company, string RequestType) {
            return base.Channel.Tally_ImportData(Company, RequestType);
        }
        
        public System.Threading.Tasks.Task<string> Tally_ImportDataAsync(string Company, string RequestType) {
            return base.Channel.Tally_ImportDataAsync(Company, RequestType);
        }
        
        public string Tally_ModifyVouchers1(HISWebApi.TallyServerProxy.VoucherData obj, string Company) {
            return base.Channel.Tally_ModifyVouchers1(obj, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_ModifyVouchers1Async(HISWebApi.TallyServerProxy.VoucherData obj, string Company) {
            return base.Channel.Tally_ModifyVouchers1Async(obj, Company);
        }
        
        public string Tally_PharmacyVoucherEntry(HISWebApi.TallyServerProxy.VoucherData obj, string Company) {
            return base.Channel.Tally_PharmacyVoucherEntry(obj, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_PharmacyVoucherEntryAsync(HISWebApi.TallyServerProxy.VoucherData obj, string Company) {
            return base.Channel.Tally_PharmacyVoucherEntryAsync(obj, Company);
        }
        
        public string Tally_PharmacyVoucherEntryTemp(string type) {
            return base.Channel.Tally_PharmacyVoucherEntryTemp(type);
        }
        
        public System.Threading.Tasks.Task<string> Tally_PharmacyVoucherEntryTempAsync(string type) {
            return base.Channel.Tally_PharmacyVoucherEntryTempAsync(type);
        }
        
        public string Tally_SalaryEntry(HISWebApi.TallyServerProxy.SalaryInfo obj, string Company) {
            return base.Channel.Tally_SalaryEntry(obj, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_SalaryEntryAsync(HISWebApi.TallyServerProxy.SalaryInfo obj, string Company) {
            return base.Channel.Tally_SalaryEntryAsync(obj, Company);
        }
        
        public string Tally_DonationEntry(HISWebApi.TallyServerProxy.SalaryInfo obj, string Company) {
            return base.Channel.Tally_DonationEntry(obj, Company);
        }
        
        public System.Threading.Tasks.Task<string> Tally_DonationEntryAsync(HISWebApi.TallyServerProxy.SalaryInfo obj, string Company) {
            return base.Channel.Tally_DonationEntryAsync(obj, Company);
        }
        
        public string CompanyNameForTally(string comp_code, string unit_id) {
            return base.Channel.CompanyNameForTally(comp_code, unit_id);
        }
        
        public System.Threading.Tasks.Task<string> CompanyNameForTallyAsync(string comp_code, string unit_id) {
            return base.Channel.CompanyNameForTallyAsync(comp_code, unit_id);
        }
        
        public string Tally_VoucherEntryNew(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherDataVertical> obj, string VoucherType) {
            return base.Channel.Tally_VoucherEntryNew(obj, VoucherType);
        }
        
        public System.Threading.Tasks.Task<string> Tally_VoucherEntryNewAsync(System.Collections.Generic.List<HISWebApi.TallyServerProxy.VoucherDataVertical> obj, string VoucherType) {
            return base.Channel.Tally_VoucherEntryNewAsync(obj, VoucherType);
        }
    }
}
